/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiUploadthingSplatRouteImport } from './routes/api/uploadthing.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin/invites'
import { Route as AuthenticatedBillsNewUploadRouteImport } from './routes/_authenticated/bills/new/upload'
import { Route as AuthenticatedBillsNewReviewRouteImport } from './routes/_authenticated/bills/new/review'
import { Route as AuthenticatedBillsNewParticipantsRouteImport } from './routes/_authenticated/bills/new/participants'
import { Route as AuthenticatedBillsNewAssignRouteImport } from './routes/_authenticated/bills/new/assign'
import { Route as AuthenticatedBillsBillIdShareRouteImport } from './routes/_authenticated/bills/$billId/share'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiUploadthingSplatRoute = ApiUploadthingSplatRouteImport.update({
  id: '/api/uploadthing/$',
  path: '/api/uploadthing/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/admin/invites',
    path: '/admin/invites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsNewUploadRoute =
  AuthenticatedBillsNewUploadRouteImport.update({
    id: '/bills/new/upload',
    path: '/bills/new/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bills/new/upload.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedBillsNewReviewRoute =
  AuthenticatedBillsNewReviewRouteImport.update({
    id: '/bills/new/review',
    path: '/bills/new/review',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bills/new/review.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedBillsNewParticipantsRoute =
  AuthenticatedBillsNewParticipantsRouteImport.update({
    id: '/bills/new/participants',
    path: '/bills/new/participants',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bills/new/participants.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedBillsNewAssignRoute =
  AuthenticatedBillsNewAssignRouteImport.update({
    id: '/bills/new/assign',
    path: '/bills/new/assign',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bills/new/assign.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedBillsBillIdShareRoute =
  AuthenticatedBillsBillIdShareRouteImport.update({
    id: '/bills/$billId/share',
    path: '/bills/$billId/share',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bills/$billId/share.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/bills/$billId/share': typeof AuthenticatedBillsBillIdShareRoute
  '/bills/new/assign': typeof AuthenticatedBillsNewAssignRoute
  '/bills/new/participants': typeof AuthenticatedBillsNewParticipantsRoute
  '/bills/new/review': typeof AuthenticatedBillsNewReviewRoute
  '/bills/new/upload': typeof AuthenticatedBillsNewUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/bills/$billId/share': typeof AuthenticatedBillsBillIdShareRoute
  '/bills/new/assign': typeof AuthenticatedBillsNewAssignRoute
  '/bills/new/participants': typeof AuthenticatedBillsNewParticipantsRoute
  '/bills/new/review': typeof AuthenticatedBillsNewReviewRoute
  '/bills/new/upload': typeof AuthenticatedBillsNewUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/_authenticated/bills/$billId/share': typeof AuthenticatedBillsBillIdShareRoute
  '/_authenticated/bills/new/assign': typeof AuthenticatedBillsNewAssignRoute
  '/_authenticated/bills/new/participants': typeof AuthenticatedBillsNewParticipantsRoute
  '/_authenticated/bills/new/review': typeof AuthenticatedBillsNewReviewRoute
  '/_authenticated/bills/new/upload': typeof AuthenticatedBillsNewUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/admin/invites'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/bills/$billId/share'
    | '/bills/new/assign'
    | '/bills/new/participants'
    | '/bills/new/review'
    | '/bills/new/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/admin/invites'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/bills/$billId/share'
    | '/bills/new/assign'
    | '/bills/new/participants'
    | '/bills/new/review'
    | '/bills/new/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access-denied'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/admin/invites'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/_authenticated/bills/$billId/share'
    | '/_authenticated/bills/new/assign'
    | '/_authenticated/bills/new/participants'
    | '/_authenticated/bills/new/review'
    | '/_authenticated/bills/new/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadthingSplatRoute: typeof ApiUploadthingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/uploadthing/$': {
      id: '/api/uploadthing/$'
      path: '/api/uploadthing/$'
      fullPath: '/api/uploadthing/$'
      preLoaderRoute: typeof ApiUploadthingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/new/upload': {
      id: '/_authenticated/bills/new/upload'
      path: '/bills/new/upload'
      fullPath: '/bills/new/upload'
      preLoaderRoute: typeof AuthenticatedBillsNewUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/new/review': {
      id: '/_authenticated/bills/new/review'
      path: '/bills/new/review'
      fullPath: '/bills/new/review'
      preLoaderRoute: typeof AuthenticatedBillsNewReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/new/participants': {
      id: '/_authenticated/bills/new/participants'
      path: '/bills/new/participants'
      fullPath: '/bills/new/participants'
      preLoaderRoute: typeof AuthenticatedBillsNewParticipantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/new/assign': {
      id: '/_authenticated/bills/new/assign'
      path: '/bills/new/assign'
      fullPath: '/bills/new/assign'
      preLoaderRoute: typeof AuthenticatedBillsNewAssignRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/$billId/share': {
      id: '/_authenticated/bills/$billId/share'
      path: '/bills/$billId/share'
      fullPath: '/bills/$billId/share'
      preLoaderRoute: typeof AuthenticatedBillsBillIdShareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedBillsBillIdShareRoute: typeof AuthenticatedBillsBillIdShareRoute
  AuthenticatedBillsNewAssignRoute: typeof AuthenticatedBillsNewAssignRoute
  AuthenticatedBillsNewParticipantsRoute: typeof AuthenticatedBillsNewParticipantsRoute
  AuthenticatedBillsNewReviewRoute: typeof AuthenticatedBillsNewReviewRoute
  AuthenticatedBillsNewUploadRoute: typeof AuthenticatedBillsNewUploadRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedBillsBillIdShareRoute: AuthenticatedBillsBillIdShareRoute,
  AuthenticatedBillsNewAssignRoute: AuthenticatedBillsNewAssignRoute,
  AuthenticatedBillsNewParticipantsRoute:
    AuthenticatedBillsNewParticipantsRoute,
  AuthenticatedBillsNewReviewRoute: AuthenticatedBillsNewReviewRoute,
  AuthenticatedBillsNewUploadRoute: AuthenticatedBillsNewUploadRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadthingSplatRoute: ApiUploadthingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
